### ISSUE TITLE
API wrapper

### ISSUE THREAD

**Issue by kphrx** [kphrx/nico-zenza#25]
# Endpoints
https://github.com/kphrx/ZenzaWatch で使ってるAPI等書き出してトラッキング

## nvapi
host: `https://nvapi.nicovideo.jp`

### activate license key
- [ ] `GET /v1/2ab0cbaa/watch?t=${trackingId}` dmc.nico のサーバーで暗号化されてる？動画に必要
### 履歴
- [ ] `PUT /v1/users/me/watch/history/playback-position` レジューム位置送信
### コメントキー
- [ ] `GET /v1/comment/keys/thread?videoId=${videoId}` `threadKey` 取得
- [ ] `GET /v1/comment/keys/post?threadId=${threadId}` `postKey` 取得
- [ ] `GET /v1/comment/keys/nicoru?threadId=${threadId}` `nicoruKey` 取得
### いいね
- [ ] `POST /v1/users/me/likes/items` いいね
### 動画タグ
- [ ] `GET /v1/videos/${videoId}/tags?_language=${i18nLanguage}` タグ一覧
- [ ] `POST /v1/videos/${videoId}/tags?_language=${i18nLanguage}&tag=${tag}` タグ追加
- [ ] `DELETE /v1/videos/${videoId}/tags?_language=${i18nLanguage}&tag=${tag}` タグ削除
### あとで見る（旧・とりあえずマイリスト）
- [ ] `GET /v1/users/me/watch-later` あとで見る取得
- [ ] `POST /v1/users/me/watch-later` あとで見るに追加
- [ ] `PUT /v1/users/me/deflist/items/${itemId}`あとで見る内動画のメモ編集
- [ ] `DELETE /v1/users/me/watch-later?itemIds=${itemIds}` あとで見るから削除
- [ ] `POST /v1/users/me/copy-mylist-items?from=deflist&to=${mylistId}&itemIds=${watchIds}` マイリストにコピー
- [ ] `POST /v1/users/me/move-mylist-items?from=deflist&to=${mylistId}&itemIds=${watchIds}` マイリストに移動
### マイリスト
- [ ] `GET /v1/users/me/mylists` マイリスト一覧
- [ ] `POST /v1/users/me/mylists` マイリスト作成
- [ ] `GET /v1/users/me/mylists/${mylistId}` マイリスト取得
- [ ] `PUT /v1/users/me/mylists/${mylistId}` マイリスト編集
- [ ] `DELETE /v1/users/me/mylists/${mylistId}` マイリスト削除
- [ ] `POST /v1/users/me/mylists/${mylistId}/items?itemId=${itemId}&description=${memo}` マイリストに追加
- [ ] `PUT /v1/users/me/mylists/${mylistId}/items/${itemId}` マイリスト内動画のメモ編集
- [ ] `DELETE /v1/users/me/mylists/${mylistId}/items?itemIds=${itemIds}` マイリストから削除
- [ ] `POST /v1/users/me/copy-mylist-items?from=${mylistId}&to=${mylistId}&itemIds=${videoIds}` 他のマイリストにコピー
- [ ] `POST /v1/users/me/move-mylist-items?from=${mylistId}&to=${mylistId}&itemIds=${videoIds}` 他のマイリストに移動
### プレイリスト
https://github.com/kphrx/ZenzaWatch/discussions/9#discussioncomment-2105331
